<?php /* @var $this Contactlab_Hub_Block_Adminhtml_Version */ ?>
<div class="grid" style="padding-top: 50px; clear: both">
    <div class="hor-scroll">
        <h3><?php echo $this->__('Checks'); ?></h3>
        <table class="data" cellspacing="0" style="width: 40%">
            <tbody>
            <?php $php = $this->checkPhpVersion() ?>
            <tr class="even">
                <td>PHP Version</td>
                <td class="last">
                    <span
                            class="contactlab-hub-event-status status<?php echo $php['code'] ?>"
                            title ="<?php echo $php['message'] ?>">
                    </span>
                </td>
            </tr>

            <?php $magento = $this->checkMagentoVersion() ?>
            <tr class="">
                <td>Magento Version</td>
                <td class="last">
                    <span
                            class="contactlab-hub-event-status status<?php echo $magento['code'] ?>"
                            title ="<?php echo $magento['message'] ?>">
                    </span>
                </td>
            </tr>

            <?php $cron = $this->checkCron(); ?>
            <tr class="even">
                <td>Cron</td>
                <td class="last">
                    <span
                            class="contactlab-hub-event-status status<?php echo $cron['code'] ?>"
                            title ="<?php echo $cron['message'] ?>">
                    </span>
                </td>
            </tr>

            <?php $hub = $this->checkModuleVersion() ?>
            <tr class="">
                <td>Contactlab Hub Version <?php echo $this->getModuleVersion(); ?></td>
                <td class="last">
                    <span
                            class="contactlab-hub-event-status status<?php echo $hub['code'] ?>"
                            title ="<?php echo $hub['message'] ?>">
                    </span>
                </td>
            </tr>

            <?php $api = $this->checkApi(); ?>
            <tr class="even">
                <td>API</td>
                <td class="last">
                    <span
                            class="contactlab-hub-event-status status<?php echo $api['code'] ?>"
                            title ="<?php echo $api['message'] ?>">
                    </span>
                </td>
            </tr>


            </tbody>
        </table>
    </div>
</div>