<?php

$installer = $this;
$installer->startSetup();
$installer->run("
	ALTER TABLE {$installer->getTable('contactlab_hub/previouscustomers')}
		DROP COLUMN is_customer,
		DROP COLUMN subscriber_id,
		DROP COLUMN is_subscribed,
		DROP COLUMN prefix,
		DROP COLUMN firstname,
		DROP COLUMN middlename,
		DROP COLUMN lastname,
		DROP COLUMN suffix,
		DROP COLUMN dob,
		DROP COLUMN gender,		
		DROP COLUMN taxvat,				
		DROP COLUMN billing_prefix,
		DROP COLUMN billing_firstname,
		DROP COLUMN billing_middlename,
		DROP COLUMN billing_lastname,
		DROP COLUMN billing_suffix,
		DROP COLUMN billing_country_id,
		DROP COLUMN billing_region_id,
		DROP COLUMN billing_region,
		DROP COLUMN billing_postcode,
		DROP COLUMN billing_city,
		DROP COLUMN billing_street,
		DROP COLUMN billing_telephone,
		DROP COLUMN billing_fax,
		DROP COLUMN billing_company,
		DROP COLUMN shipping_prefix,
		DROP COLUMN shipping_firstname,
		DROP COLUMN shipping_middlename,
		DROP COLUMN shipping_lastname,
		DROP COLUMN shipping_suffix,
		DROP COLUMN shipping_country_id,
		DROP COLUMN shipping_region_id,
		DROP COLUMN shipping_region,
		DROP COLUMN shipping_postcode,
		DROP COLUMN shipping_city,
		DROP COLUMN shipping_street,
		DROP COLUMN shipping_telephone,
		DROP COLUMN shipping_fax,
		DROP COLUMN shipping_company,		
		DROP COLUMN store_name,
		DROP COLUMN website_id,
		DROP COLUMN website_name,
		DROP COLUMN group_id,
		DROP COLUMN group_name,
		DROP COLUMN language,
		DROP COLUMN extra_properties
");
$installer->endSetup();